### ISSUE TITLE
Implement middleware support

### ISSUE THREAD

**Issue by alemagio** [alemagio/fastify-postgraphile#1]
As discussed [here](https://github.com/graphile/postgraphile/issues/1220#event-3930747342), once the change will be released postgraphile will offer an api to use the middleware in fastify too.
So, once that will be released, we want to implement support for that API.

**Comment by alemagio** [comment]
Changes have been released so this might be the good time to handle this.

**Comment by alemagio** [comment]
It should be necessary just follow [this](https://github.com/graphile/postgraphile/blob/v4/examples/servers/fastify3/vanilla.ts) example.

**Comment by acg-thp** [comment]
So are you thinking of only using the specific parts from the postgraphile library to get this working? (I'm still trying to wrap my mind around it, ill probably pull down that example and run it separate just to see how it works)

I see we have a queryPerformer, a way to createSchema from the database... 

What is ```fastify.options(middleware.graphqlRoute, convertHandler(middleware.graphqlRouteHandler));``` graphqlRoute/graphqlRouteHandler suppose to be?

**Comment by alemagio** [comment]
This is my idea.
I would add an option called `middleware` default to true.
If true we should simply skip what the plugin is doing now and just delegate everything to the middleware.
If false, avoid the middleware and leave the thing as it is now.
Does it make sense?

**Comment by acg-thp** [comment]
Yes I think it makes sense, I am not (should be) familiar with the term middleware.

So we have a check on opts.middleware and if true then run middle ware code as seen/understood in example, otherwise run the code we are already running.

Ill take a shot at it tonight and let you know how I manage!

**Comment by alemagio** [comment]
No problem, if something is not clear just ask.
Give it a try as you think it might be fine and push it. It'll be easier to discuss while watching the code :smile:

**Comment by acg-thp** [comment]
Alright I think I have got it working, I am not to familiar with Typescript but I can push up a change tonight/tomorrow to a sperate branch for you to take a look it. All It does currently is just exactly what was in the example and the user passes in some values in options
```
pool: {
    user: 'user',
    host: 'localhost',
    database: 'user',
    password: 'localhost',
    port: 5432
  },
  database_uri: "postgres://user:localhost@localhost:5432/user",
  schemas: 'public',
  middlewareEnabled:true,
  middleware_options: {
    graphiql: true
  }
```
and then inside we just run a conidition on middlewareEnabled to determine which function to run. 

I'm going to try and clean up some of it and commit something up soon but I did test it and it does work against the database and provides us the graphiql route needed for frontend developers

NOTE: I am not sure about how the user wants to pass in the pool arguments or as a database_uri

**Comment by acg-thp** [comment]
https://github.com/acg-thp/fastify-postgraphile/tree/middleware_integration

There is a few more things needed to be done, like I understand I need to make interfaces for typescript to be used properly.

I have not tested the watchPg yet but i know the graphiql setting works. So a few more modifications to 'pretty it up' and let me know what else you'd like it to do/ fixes as again I am not to familiar to TS yet..

**Comment by acg-thp** [comment]
For the middleware integration, I believe we should be able to use options to enable other postgraphile features correct (Ones that may not be present in the example but are documented features of postgraphile)?

**Comment by alemagio** [comment]
In theory once enabled middleware you should be able to pass any option available in postgraphile to it.

**Comment by alemagio** [comment]
@acg-thp 
Hi, any update?
