### ISSUE TITLE
Automatic route

### ISSUE THREAD

**Issue by alemagio** [alemagio/fastify-postgraphile#3]
Postgraphile adds automatically a `/graphql` route which can be eventually be customized throw option.
We need to make it also possible (maybe making it optional too) and also allow the user to customize the name of such route.

**Comment by alemagio** [comment]
Closed by #1 
In middleware mode it is possible to have automatic route.

**Comment by mariusa** [comment]
Hi,

> allow the user to customize the name of such route

Does this work via `graphqlRoute` option at https://www.graphile.org/postgraphile/usage-library/ ?


> Postgraphile adds automatically a /graphql route which can be eventually be customized throw option

Would you please add this in README?
I have a hard time getting started:

```
    fastify.register(require('fastify-postgraphile'), {
        pool: {
            connectionString: process.env.DATABASE_URL
        },
        schemas: 'public',
        middleware: true,
        postgraphileOptions: {
            // all the options you can pass to the postgraphile function
        }
    })

```

What would be the next steps to have a working query?

Would you please provide an example too? eg
```
curl -v -X POST -H "Accept: application/json" -H "Content-type: application/json"  -d '..???..' http://localhost:5000/graphql
```

Thanks

**Comment by mariusa** [comment]
Progress: having an `org` table, this works at http://localhost:5000/graphql
```
query allO {
  allOrgs {  nodes { id name }} 
}
```

**Comment by alemagio** [comment]
Hi, happy to see this plugin is useful :smile: 

BTW yes if I do remember correctly the path to the `graphqlRoute` option should be:
```js
{
  options: {
    middleware: {
      graphqlRoute: '...'
    }
  }
}
```
as documented [here](https://github.com/graphile/postgraphile/blob/209d74cf5ade669590efb15b3e45cbfa5f58724d/examples/servers/fastify3/vanilla.ts#L29)

Thanks also for the suggestion in the doc, I'll open an issue as soon as I can but please feel free to open it yourself and, why not?, also opening a PR with your suggested changes :smiley:
