### ISSUE TITLE
Add GraphIQL Support From PostGraphile

### ISSUE THREAD

**Issue by acg-thp** [alemagio/fastify-postgraphile#5]
https://www.graphile.org/postgraphile/usage-library/

I will try to look into this tomorrow, from the documentation it looks like we just need to add an option to enable it during development and ensure its disabled during production.

**Comment by alemagio** [comment]
Hi @acg-thp , thanks for contributing first of all!
The thing might not be so simple I believe.
We need, first, to make a little bit of changes first as explained [here](https://github.com/alemagio/fastify-postgraphile/issues/1).
If you feel confident you can also try to do that, I'll answer every question you have off course.
If not, I have planned to work on that and hopefully I'll be able to ship it in a few days.

**Comment by alemagio** [comment]
Closed by #1
